### ISSUE TITLE
People page copy edits

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#115]
New copy:

Diverse Members, One Mission

Network members speak many languages and span many disciplines. But we all believe in a healthy Internet. Here are a handful of members making a difference: 

 - [x] Update [prototype](https://invis.io/ZJ9YTAGEA#/216715355_Home-Page-Opt1)
 - [ ] Update [staging](https://network.mofostaging.net/)

**Comment by taisdesouzalessa** [comment]
Updated prototype [here](https://invis.io/ZJ9YTAGEA#/221081570_People-Front-Card).

IMPORTANT: since now we don't have the filter anymore (for V1): digital inclusion, web literacy and so on I removed the link treatment from the tags. To differentiate role of the person and interests I had to do some changes:

![people-changes](https://cloud.githubusercontent.com/assets/22157921/23777250/04f400d6-04e8-11e7-96ac-216dc8d7d8bc.png)

1. Weight changed to Bold
2. Weight changed to Light Italic AND color to Black (it was Blue)
