### ISSUE TITLE
People page / front end of CMS issues

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#149]
- [x] Featured people aren't showing any differently than non-featured people (_Fix in: Django_)
   - [x] Can't verify that bio appears (though I assume the bullet points and line breaks I put in the field won't render)
   - [x] Can't verify that card flip functionality works as expected
   - [x] Can't check that quote appears on back of card
 - [x] People with multiple affiliations—no semicolon and space between affiliations
 - [x] Links not visible; likely due to lack of clarity in https://github.com/mozilla/network-api/issues/43#issuecomment-286265514
 - [x] in the case where there's no partner logo, should not display an "image not available" image (_Fix in: Django_)
 - [x] need to consider whether there should be a max height on the partner image

cc @sabrinang @taisdesouzalessa

**Comment by hannahkane** [comment]
I'd prioritize fixing the "no image available" issue, because that doesn't look great. Otherwise, I don't think these things are blockers to soft launch.

**Comment by cadecairos** [comment]
> in the case where there's no partner logo, should not display an "image not available" image

This is related to the admin interface not enforcing it as a required field. We'll file an issue to change that

**Comment by gvn** [comment]
Well, I don't think we should make partner logo required because not everyone will have one unless I'm mistaken @hannahkane ?

We can just suppress the "Image Not Available" visual on the front end if there's no logo.

**Comment by gvn** [comment]
Since Alan is traveling I'm going to look into fixing this.

**Comment by sabrinang** [comment]
From issue https://github.com/mozilla/network/issues/100#issuecomment-284528827, it was mentioned that "People on Partners tab also get a logo, BUT only when the new logo column is highlight bright green too." so I believe we display around 10 of those approved partner orgs for the highlighted green people but I am unsure about that status on the rest.

**Comment by hannahkane** [comment]
Yes, partner logo should not be required, but "image not available" image should be suppressed.

**Comment by gvn** [comment]
I've identified a few issues with the JSON being emitted from Django:

@gideonthomas @cadecairos :

`featured` isn't being emitted on any of the items returned. Is this because none are featured or does that property not exist in Django?

`links` is formed differently in the data from Django:

Django:
```
    "links": [
      {
        "url": "https://storyengine.io/stories/decentralization/joe-mcnamee/",
        "name": "Story Blog"
      }
    ],
```

Expected:
```
      "links": {
        "type": "object",
        "properties": {
          "twitter": {
            "type": "string"
          },
          "linkedIn": {
            "type": "string"
          }
        }
      },
```

**Comment by gvn** [comment]
Looks like only featured cards are "flippable", so once the `featured` property is set to true on a person the flipping should work as expected.

**Comment by gvn** [comment]
Links will just not render with the current structure coming out of Django. Will require a refactor of FE to display.

**Comment by gideonthomas** [comment]
Will make the above fixes! Thanks!

**Comment by hannahkane** [comment]
OK, as per [Gideon's comment](https://github.com/mozilla/network-api/issues/49#issuecomment-286552201), the formatting fix for the bio field is a front-end fix.

Dang, I did a bad job of filing issues in the right repos. Sorry!

**Comment by gvn** [comment]
The only things remaining to do from my perspective are:

- [ ] Links need to be suppressed if they are an empty string. Django returns empty strings instead of null for some reason.
- [ ] Georgia Bullen is missing a photo and it's showing the "No Image Available" circle. I'm guessing we want to either hide that or come up with a better generic portrait image.
- [ ] Portrait and affiliate logo need a little margin between them.

**Comment by hannahkane** [comment]
Thanks, @gvn. I think we can require images of the people themselves. I didn't see an image for Georgia in the folder, though I do see a link to one in the spreadsheet. @sabrinang - can you please advise - do we have a photo of Georgia to use?

**Comment by gvn** [comment]
I'm suggesting that we do the same thing we do for logos when they're unavailable, which is return `null` from Django and not show a placeholder on the front end.

For the moment if we can just put Georgia's photo in then we can address that point after launch.

**Comment by hannahkane** [comment]
Thanks, @gvn. I understood what you're suggesting. I don't think we will want to have profiles without an image of the person (I could be wrong about that), so I was counter-suggesting that we make it required to have a non-default image there. But agree we can table this until later.

**Comment by gvn** [comment]
Ah, ok. If we want to make the profile photo a required field that precludes the need for any front-end refactoring.

**Comment by sabrinang** [comment]
@hannahkane I updated the folder (to include Georgia and Daniel) https://drive.google.com/drive/folders/0B4Q8pzCpDS_eUzFlYnZ0TGpOUG8?usp=sharing

**Comment by taisdesouzalessa** [comment]
This is so nice to see! 

Besides the items @gvn added to the checklist, there are some visual elements present in the comp that should be added to the page:

- [ ] slants in the featured cards

- [ ] typeface in the quotes have "font-style:italic" instead of using "Nunito Sans Light Italic"

- [ ] If it is not possible to break lines through the use of bullet points we may want to rewrite the bullet points in a more descriptive way.

- [ ] I would love to tweak the animation (I am sure this is not a priority, just adding as a reminder).

I am not sure about the priorities of those changes, definitely not an MVP. 

I agree with @hannahkane that the pictures should be a requirement because this page is to highlight people of the Network and seeing their faces helps the connection to be established.

Last, sorry if I missed it, but will we be able to manually sort the people to control how the grid shows up? Fir instance, it would be nice to have another person beside Teon

**Comment by hannahkane** [comment]
@taisdesouzalessa - we can sort using the django interface. I'm happy to make any adjustments you'd like, or you can go in yourself, but know that I'll be adding a few more people today.

**Comment by hannahkane** [comment]
thanks, @sabrinang, for the images!

**Comment by hannahkane** [comment]
just re-ordered the cards, so should look better once we rebuild

**Comment by taisdesouzalessa** [comment]
That's awesome, Hannah. Thank you so much for that :). Let me know if you need any help on adding more people or sorting cards.

**Comment by hannahkane** [comment]
- [ ] LinkedIn links aren't showing up

**Comment by gvn** [comment]
LinkedIn is fixed on staging

**Comment by xmatthewx** [comment]
@hannahkane - seems like this is all fixed. true? ready to close?

**Comment by hannahkane** [comment]
There are some unchecked boxes [here](https://github.com/mozilla/network/issues/149#issuecomment-286807775), but I'll close this and open a new issue instead.
