### ISSUE TITLE
Consider copy changes for People page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#162]
This list updated per comments below:
- [ ] Remove “:” at the end of the hero text
- [ ] change the link that points here from the homepage from "See Network members" to "Member spotlight" 
- [ ] Add a "Member spotlight" header above cards

---

Matthew points out that we haven’t solved problem of this looking like a comprehensive list of members yet. I'm not sure this will be solved with Hero text. Wondering if we need to add a header above the first row of cards? Or perhaps add a "you two can join the network"-style CTA somewhere?

Thoughts, @xmatthewx and @KevZawacki?

**Comment by xmatthewx** [comment]
Thanks. I think the link that points here from the homepage could say "Member spotlight" or something similar instead of "See Network members". 

We could put a "Member spotlight" header above cards too. 

Let's not add a CTA at this stage. We've hit pause on Join, running with list Sign up right now.

**Comment by sabrinang** [comment]
Invision screens updated:
- People: https://projects.invisionapp.com/d/main#/console/10016110/216715363/preview
    - Removed “:” at the end of the hero text
    - Added a "Member spotlight" header above cards
- Home: https://projects.invisionapp.com/d/main#/console/10016110/216715355/preview and https://projects.invisionapp.com/d/main#/console/10016110/223997779/preview
   - Link text updated to "Member spotlight"
