### ISSUE TITLE
Optimizing Sign-up & Opt-in experience

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#207]
When a user submits the sign-up form via the Network site, they receive an email and link to opt-in. This takes them to the screen below. 

As currently implemented (and as you probably already know), this gives users a fairly confusing experience. Do we have the agency to make some improvements?

 1. Can we customize this screen? Build a branded version within our site?
 1. If so, can we change the order of items, moving Firefox to the bottom?
 1. Is our plan to consolidate foundation, learning, and network?
 1. Lastly, can we call the list Mozilla Network, removing the word leadership? We're unlikely to use the word on the site. (Let's discuss before we jump to change it.)

cc @WillatMozFdn @HPaulJohnson @arlissc @stephaniemcv @Lottarao 

<img width="1119" alt="screen shot 2017-03-20 at 5 49 07 pm" src="https://cloud.githubusercontent.com/assets/53411/24123375/98090f96-0d95-11e7-9076-620c142f0baf.png">

**Comment by stephaniemcv** [comment]
1. Absolute customization is probably not possible. @WillatMozFdn  and I will be working with MoCo on a project whose focus is to  improve the preference center, not only the look to be more on brand, but moving from strictly lists to incorporate interests. @arlissc is gathering a starting list of interests for the Network.
2. We may be able to change some of the order, but I doubt we'll be able to get Firefox at the bottom, as they beat out all our lists in terms of numbers of subscribers. 
3. The plan was to merge Network and Learning. The idea was floated to merge all three, but I believe we nixed that, @WillatMozFdn correct me if I'm remembering incorrectly.
4. Yes, we can remove the word leadership. We also need a 140 character description of the Network so people know what they've signed up for.

**Comment by WillatMozFdn** [comment]
Affirmative on all of Stephanie's replies below (thanks Stephanie!), plus some added details and a new to-do item as #5 ....

#2: Yes, this page is currently the overall preference center for everything MoFo and MoCo; Firefox is at the top since (as a much bigger list than all the others combined) it drives the vast majority of traffic to this page.  As Stephanie mentioned, this page will be overhauled over the next several weeks to give users more control over their interest areas, and give us more flexibility to target by those interest areas and not just on the basis of "lists."

#3: Correct, the plan right now is that with sunsetting the "Mozilla Learning Network" list (we're not publishing content specifically for these subscribers anymore), these folks will all be moved to the new "Network" subscription, with interest areas tagged based on their previous subscription(s).

#4: Yes, we definitely need that description of the Network subscription so page visitors understand why they would want to opt in and what's in it for them.  Related to that....

#5: Is anyone (Kevin?) working on a welcome email (not just the confirmation email to get you subscribed via double-opt-in) designed specifically for the new Network subscribers?  The current MoFo Advocacy one is here to use as a starting point ... https://docs.google.com/document/d/11CsSNAyOWli0apeWEw11K6iEhhiJuEeC9hOjJ0aEL10/edit ... this is definitely something we should have in place before we start signing up new people from the Network site.

 - Will

**Comment by xmatthewx** [comment]
Thanks for the all the info. Please let me know if there's any way I can support your work. Would you like a designer to join your conversation with MoCo on the preferences dashboard?

I wonder if the description for the Network subscription you've requested should come from 270? I will inquire and report back. If not, I can provide something.

**Comment by stephaniemcv** [comment]
Thanks for checking with 270 about the description! Do you have a recommendation on which designer we bring in when we get to that point in the conversation?

**Comment by xmatthewx** [comment]
@stephaniemcv – if they'll just be an advisor making suggestions, anyone would be great, depending on their other workload. They would need some orientation on the constraints if and when you pull them in. Taís has done most of the UX for the site and is probably first in line.

**Comment by xmatthewx** [comment]
@taisdesouzalessa continued this work in #503
