### ISSUE TITLE
Design a Member Preview notice

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#227]
Design a notice for top of the site. Says Welcome to the Member preview. Includes link to a feedback form.
 - Can use our previously built notice component 
 - Copy from Lotta/270
 - Engagement form by Chris/270
 - Leverage Coral / Google form as fallback

**Comment by xmatthewx** [comment]
Here's an option that keeps things super simple. This would appear on all pages. Static. No need to dismiss or hide on subsequent visits. 

<img width="1120" alt="screen shot 2017-03-30 at 5 30 35 pm" src="https://cloud.githubusercontent.com/assets/53411/24527106/d090ee3e-156e-11e7-9c5c-88039f7b3ae8.png">

Moves up on scroll.

<img width="1120" alt="screen shot 2017-03-30 at 5 30 54 pm" src="https://cloud.githubusercontent.com/assets/53411/24527107/d0911bca-156e-11e7-8294-23340da38113.png">

Menu & logo stick to top, but notice scrolls away. 

<img width="1119" alt="screen shot 2017-03-30 at 5 31 10 pm" src="https://cloud.githubusercontent.com/assets/53411/24527105/d0909966-156e-11e7-8543-556ddec733c7.png">

**Comment by taisdesouzalessa** [comment]
I think it is a good solution @xmatthewx. Simple and direct. I would guess the banner shows up again when the users scroll all the way to the top? 

My only suggestion would be to add a bit of more excitement to the message, since it is a exclusive preview for members. I think by showing them the exclusivity we can encourage more feedback forms filled. Like "You are one of the first ones seeing this site. Your feedback is very important to us." - okay I am not good with copy but hopefully I could transmit the message.  We could also add little icon before the words to add some delight to the preview experience. What do you think?
<img width="127" alt="screen shot 2017-03-30 at 4 30 06 pm" src="https://cloud.githubusercontent.com/assets/22157921/24530413/9c431b32-1566-11e7-8bf6-997274ce6f0f.png">

**Comment by taisdesouzalessa** [comment]
@xmatthewx will we be able to track if the feedback came from a user on mobile or desktop? I am interested to know where they are coming from to look at the feedback through the right lenses, considering their context.

**Comment by xmatthewx** [comment]
We could track how many mobile users click to give feedback, vs desktop. We can't carry that data to the survey in any easy way. We would need to ask in the survey (weighing that against other priority questions).

**Comment by xmatthewx** [comment]
We can let our consultants and copywriters compose the statement, align it with language in their emails and survey. 

We can recommend possible questions for the survey, but that survey will be optimized for return rates. Within our team, we can do some remote usertesting to learn about site performance for a broader audience.

**Comment by xmatthewx** [comment]
Thanks all. Closing this. Implementation will continue #252.
