### ISSUE TITLE
Implement Member preview notice

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#252]
Top of the site will include a simple notice to visitors to flag this as a member preview.

Requirements: Nothing fancy. This would appear on all pages. Static. No need to dismiss or hide on subsequent visits. Copy with a link. 

Let's start with an estimate of effort.

**Comment by xmatthewx** [comment]
Styles used to create mockup below:
```
    background: lightyellow;
    padding: .75em 1.5rem;
    line-height: 1.2em;
    text-align: center;  
```

Small screen: 

<img width="412" alt="screen shot 2017-03-31 at 11 47 12 am" src="https://cloud.githubusercontent.com/assets/53411/24558069/e8418e5a-1607-11e7-8329-6afcd9ebc811.png">

Big screen: 

<img width="1120" alt="screen shot 2017-03-30 at 5 30 35 pm" src="https://cloud.githubusercontent.com/assets/53411/24527106/d090ee3e-156e-11e7-9c5c-88039f7b3ae8.png">

Moves up with page on scroll. Just default relative position. 

<img width="1120" alt="screen shot 2017-03-30 at 5 30 54 pm" src="https://cloud.githubusercontent.com/assets/53411/24527107/d0911bca-156e-11e7-8294-23340da38113.png">

Menu & logo stick to top, but notice moves as default with rest of page. Still there when user scrolls back to top. Nothing fancy. Just default relative position.

<img width="1119" alt="screen shot 2017-03-30 at 5 31 10 pm" src="https://cloud.githubusercontent.com/assets/53411/24527105/d0909966-156e-11e7-8543-556ddec733c7.png">

**Comment by xmatthewx** [comment]
URL for feedback link: https://mzl.la/2ohCL8O

**Comment by xmatthewx** [comment]
@taisdesouzalessa feel free to suggest refinement to type or choose a color in our palette if necessary. Otherwise, give a thumbs up to proceed.

**Comment by taisdesouzalessa** [comment]
@xmatthewx the yellow of our palette is too strong (even the light one) and it competes with the button. I think it is ok to use the yellow you suggested since this is just a temporary banner.

Another option is to use the grey in our palette (#f2f2f2)

My other recommendation is to use Nunito Sans Light Italic for copy and Bold Italic for link. Since we won't add any icon to this notice I think adding italic helps to give the feeling of being a notice, different from the rest of the page's copy.

<img width="1033" alt="screen shot 2017-03-31 at 4 36 59 pm" src="https://cloud.githubusercontent.com/assets/22157921/24572766/8b53925a-1630-11e7-9db0-afb04a8b4c39.png">

**Comment by gvn** [comment]
Looks like this isn't ready for engineering. Feel free to move it back when design is finalized.

**Comment by xmatthewx** [comment]
Type: let's use @taisdesouzalessa's suggestions (if we're already loading those fonts)
 - Nunito Sans Light Italic for copy
 - Nunito Sans Bold Italic for link 

Background color: 
 - let's "lightyellow" if possible. if not #f2f2f2 from our palette.

**Comment by gvn** [comment]
@xmatthewx Are you implementing this ticket or can I unassign you?

**Comment by xmatthewx** [comment]
Yes. I just wanted to put a hold on it until I had talked through the feedback with Chris. Good to go now.
