### ISSUE TITLE
Remove "Network" from site logo

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#286]
- [ ] Remove from asset (design)
 - [ ] Replace asset (engineering)

**Comment by sabrinang** [comment]
Replace with mozilla logo on gdrive here: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eQVhTRFRoYjhoS2M?usp=sharing

<img width="1367" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/24884363/df3a1be4-1dfd-11e7-8db9-916a5f58bfeb.png">

**Comment by hannahkane** [comment]
Thanks, @sabrinang! If this is ready for engineering, could you move it to the right pipeline? If you have zenhub installed, you can either doing that by going to the "Boards" tab and click-and-drag, or you can do it directly from the ticket itself - the "Pipeline" field is at the top of the ticket, above the "Assignees" field.

**Comment by sabrinang** [comment]
I’m a bit hesitant of the generic mozilla logo from a comms understanding perspective but I understand this doesn’t have a name yet for launch. Even though this is a small wordmark I think it serves a larger purpose of a title that orients the user in the diverse landscape of mozilla.

We may need to consider the heading to introduce ‘mozilla network’ as a concept or it may seem like we are describing mozilla as a whole.

Our network copy:
**heading:** We Are Champions of a Healthy Internet
**subhead:** A global network dedicated to an open and accessible internet for all.

It is already very similar to mozilla.org copy:
**heading:** Internet for people,  not profit. 
**subhead:** Hi. We’re Mozilla, the proudly non-profit champions of the Internet, helping to keep it healthy, open and accessible to all. 

The about page does use more of this Mozilla Network language and Network is referenced throughout the site, can we surface it earlier on the homepage if this wordmark is removed? or if the concern is calling it Mozilla Network we already reference network or network members in many of our page descriptions. I'm wondering if removing the wordmark (that sorta serves as our site title) will hinder the understanding of the network since we use network language throughout the site already.

@xmatthewx Thoughts or feedback?

**Comment by xmatthewx** [comment]
Logo is good for engineering. We will file a separate ticket for other concerns and I will bring back to the execs. Not a blocker for implementation.

**Comment by mmmavis** [comment]
@sabrinang can you help trim the whitespace around the logo?
<img width="1438" alt="screen shot 2017-04-12 at 4 55 30 pm" src="https://cloud.githubusercontent.com/assets/2896608/24984194/e3ffc5e4-1fa0-11e7-8d0c-669127fad8f6.png">

**Comment by sabrinang** [comment]
@mmmavis that file is updated now! (weird, it was from the logo files that were sent out previously)
