### ISSUE TITLE
Switch to Zilla

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#303]
Feedback from brand team: 

Web fonts are now available for both Zilla and Zilla Highlight

 - [ ] Replace all instances of Tesla and Arvo. 
 - [ ] Hero headers – use Zilla _regular_ not _bold_ weight

**Comment by xmatthewx** [comment]
Queued up for next heartbeat. Good to consider while tackling other QA tickets cc @alanmoo @gvn @taisdesouzalessa @sabrinang

**Comment by taisdesouzalessa** [comment]
UPDATE from Yuliya about Zilla: 

> The mozilla.org team is hosting it for mozilla.org. Ping Craig Cook if you want to get access to it.

Otherwise it seems the font will be available next week - I asked if the font would be hosted in something like Google Fonts.

Not sure if the team wants to implement this typeface soon and if we can wait until next week. Thoughts on that @xmatthewx @gvn @alanmoo @sabrinang? I would like to run some tests locally first to see if there are any tweaks necessary once we change to Zilla.

**Comment by taisdesouzalessa** [comment]
Update: Zilla is on Google Fonts but not the highlighted version.
https://fonts.google.com/specimen/Zilla+Slab

**Comment by xmatthewx** [comment]
That's too bad the highlight font isn't ready yet.

**Comment by taisdesouzalessa** [comment]
@xmatthewx we have the highlighted variant in Google Fonts:  https://fonts.google.com/specimen/Zilla+Slab+Highlight - however, as @fitojb mentioned, the character coverage is not complete yet, which may result in challenges for localization.

**Comment by xmatthewx** [comment]
@taisdesouzalessa - that might be okay since we aren't yet localized. but... that will also require a bit more work to redo the ways we fake the highlight right now. 

I suggest we run with plain Zilla for now, and revisit the highlight version later. I'm also curious what @gvn thinks.

**Comment by taisdesouzalessa** [comment]
Status: will work with @flukeout  to help me to set up a local environment for that today and then I'll be able to see @fitojb's changes, yay! We will need to do some design tweaks later on and I'll need @kristinashu's eyes on the tweaks I do to make sure it is aligned with her UI strategy. Also, it would be nice to have @sabrinang's eyes on the task as well. I will coordinate with the designers to make sure we are all aligned.

**Comment by taisdesouzalessa** [comment]
In general, this change is ok on both desktop and mobile. The only issue I found was related to smaller sizes of Zilla. Because the x-height of Zilla Slab is smaller than its predecessor (Arvo) we have almost no contrast between h5 and body copy, for instance, which is not great for scannability.

<img width="870" alt="image" src="https://user-images.githubusercontent.com/22157921/32468522-7ae74a94-c303-11e7-855f-496782e5c9b6.png">

My suggestion is to push Zilla Slab to prod since it is not a huge issue and it is important for our brand alignment. I'll file a ticket though, in which @sabrinang @kristinashu and I should work together, tweaking the current hierarchy system to improve scannability with Zilla, following our brand guidelines. 

@gvn could you please add here that cool URL with all the styles of the site on one page? I remember you built something like that. That would help us to visualize the current system.

**Comment by gvn** [comment]
Yep, totally: https://foundation.mofostaging.net/style-guide/
