### ISSUE TITLE
Add textures to site

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#330]
There are a variety of spots that had background images in the designs; We should identify and add them. @sabrinang or @taisdesouzalessa can you do a review of the site for elements like this (the join component and the site heading come to mind) and link the image assets here so dev can implement?

**Comment by taisdesouzalessa** [comment]
@alanmoo when we add the background to the heading section, could we also increase padding top and bottom to 80px instead of the current 24px?

Initially Sabrina designed this heading in a way that the texture goes all the way up to the nav (I am not sure how we can do it):
<img width="515" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25597379/3d1dc5b8-2e83-11e7-8b3a-b8539cd9c91e.png">

Also, I imagine you'll need other image sizes to different break points - or do you have another technique in mind? Let's sync once you have this task on your plate.

Here are the textures, in JPG and PNG (both @2x). 

- This first texture is for the CTA (it is a white PNG - that is why it looks empty. It is here, though :))
![cta-bkg 2x](https://cloud.githubusercontent.com/assets/22157921/25597441/8e186734-2e83-11e7-976b-09538eabafbf.png)

- This texture is for the hero:
![hero-bkg 2x](https://cloud.githubusercontent.com/assets/22157921/25597442/8e2d9172-2e83-11e7-84f5-a5b0aa20fb32.jpg)

cc: @sabrinang

**Comment by xmatthewx** [comment]
no relevant.
