### ISSUE TITLE
Links in Join component do not work

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#351]
When attempting to add a link to the description of a signup component (https://network.mofoprod.net/admin/landingpage/signup/1/change/), there seems to be some issues with encoding of quotation marks that causes the string to only partially render (the link and everything after it disappear).

Since the component is being generated by a data attribute that react then uses, I believe the problem is in the front end code. Perhaps something needs to be done when passing the props to react.

**Comment by gvn** [comment]
I'm about 99% sure this is because of `"` not being escaped, which is going to break the markup because it's interpreted as the end of the data attribute's value. This is just fundamental HTML behavior.

EG: `data-cta-description="<p>What's next? <a href="` is all that gets parsed.

I believe we have to solve this by encoding all entities (or at a bare minimum encoding `"` or using `'` instead of `"` for HTML fragments). 

Is this something Mezzanine can do? @alanmoo @Pomax

**Comment by alanmoo** [comment]
Yeah, that is the problem, I'm not sure if there's a way to tell Mezzanine to do that, at least easily: The editor seems to like automatically converting `'` to `"` when saving, so we can't easily work around this when needed. Maybe there's something I'm missing though, wanna play around with the staging server and see if you can coax it into working, using HTML entities or something?
