### ISSUE TITLE
Align hero headings

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#360]
1) Hero heading on homepage aligns left with Menu. Nice!

<img width="1680" alt="screen shot 2017-04-27 at 1 25 07 pm" src="https://cloud.githubusercontent.com/assets/53411/25506844/af7f122a-2b76-11e7-94e9-b7da03a1853d.png">

2) On other pages, hero heading aligns (almost) with the logo. This squishes the text and creates an odd gap. 

<img width="1680" alt="screen shot 2017-04-27 at 1 24 50 pm" src="https://cloud.githubusercontent.com/assets/53411/25506864/ccd5ce2c-2b76-11e7-8188-0e6497ffb1e1.png">

3) Also, secondary pages have light font-weight (nice!). Homepage has bold, which is too heavy. It also jumps up to 64px on wide screens, which feels too big.

**Comment by xmatthewx** [comment]
curious what you think @taisdesouzalessa

**Comment by taisdesouzalessa** [comment]
I think they are great steps for a more polished page @xmatthewx 

- The issue number 2 already has a ticket here: #341 - hopefully we can fix it in this heartbeat. 
- For the number 3, I agree we can make the home page font lighter and probably smaller too. I was using multiples of 8px for typeface so the next one is 54px, displayed below:
<img width="1077" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25509680/a2c73870-2b6f-11e7-9402-d53455ed680d.png">


If we go with 54px I think we have to increase the margin top and bottom to make this hero section stronger. Also there is something missing in the right side: we should add the abstract shapes Sabrina worked on. It adds more personality to this part. It is important because the copy has a lot of personality and the design should help reinforce that (and now it is very plain), what do you think?

**Comment by xmatthewx** [comment]
Let's close this issue and add a note about font weight to the other issue. Can we just make the large heading on all pages the same? Simplify. 

While I do want to add shapes to the hero, let's file that as a separate ticket. It's less critical than these other things.

**Comment by taisdesouzalessa** [comment]
Closing this issue - font weight discussion in #365
