### ISSUE TITLE
Copy change: "Support" -> "Get Involved"

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#402]
Request is to change the name of this Nav item/page to better signal the kind of engagement we're looking for.

**Comment by sabrinang** [comment]
related to ticket https://github.com/mozilla/network/issues/322

**Comment by hannahkane** [comment]
@hannahkane to discuss with stakeholders - implications include a) longest string in nav menu; b) page already has "Get Involved" button on it

**Comment by xmatthewx** [comment]
I don't think the string is tooooo long. Just mentioned for estimation.

**Comment by sabrinang** [comment]
Just pointing out another area we also use this language on our site and that it could cause confusion on what the nav item leads too: 
![screenshot-get-involved-language](https://cloud.githubusercontent.com/assets/2492510/25828351/9977cb48-3404-11e7-929a-a3d3de6de15a.jpg)

**Comment by hannahkane** [comment]
@xmatthewx @sabrinang - what do you think about changing the yellow button to "Get Connected", keeping "Get Involved" for the homepage, and renaming the Support page "Get Involved"?

**Comment by xmatthewx** [comment]
I'm cool with Get Involved for the Support page. Agree that we need to revisit the button. I'd like to loop in Jesse for the final call.

Context: MoFo was doing a dance to avoid the word Join because we had uncertainty around the notion of membership. Personally, I think we can still work to clarify membership and use the word join. 

I know the dance has been tiring, but it's complicated and this button is highly prominent.

Here are pro/cons for some top candidates.

### Join

Pro: Clear and simple
Con: Triggers questions about what it means to join 

<img width="838" alt="screen shot 2017-05-11 at 9 44 01 am" src="https://cloud.githubusercontent.com/assets/53411/25952381/841c9144-362e-11e7-9be7-2f259c4c1ec7.png">

### Connect

Pro: Simple call to action.
Con: Is it ambiguous?

<img width="838" alt="screen shot 2017-05-11 at 9 44 48 am" src="https://cloud.githubusercontent.com/assets/53411/25952382/841d8b76-362e-11e7-918d-7137abc13b63.png">

### Get Involved

Pro: Clear and direct
Con: Collides with other CTAs and Nav

<img width="837" alt="screen shot 2017-05-11 at 9 42 32 am" src="https://cloud.githubusercontent.com/assets/53411/25952288/46c2c624-362e-11e7-9038-20f54bca1aa7.png">

### Connect with Us

Pro: Friendly and welcoming
Con: Looong for a button. "Us" might be read as Mozilla.

<img width="839" alt="screen shot 2017-05-11 at 9 42 59 am" src="https://cloud.githubusercontent.com/assets/53411/25952287/46ba75dc-362e-11e7-8c34-3ce1daefdeab.png">

### Get Connected

Pro: Avoids other pitfalls
Con: Awkward, passive voice

<img width="838" alt="screen shot 2017-05-11 at 9 44 19 am" src="https://cloud.githubusercontent.com/assets/53411/25952383/8424a6f4-362e-11e7-9c6a-516f4c495f7d.png">

**Comment by hannahkane** [comment]
All of these options actually feel more burdensome than I think we need to be. As we state on the page itself, what the user is actually doing here is "Signing up for opportunities and news related to a healthy internet."

Could we use "SIGN UP" until we have a more precise/meaningful definition of joining?

**Comment by xmatthewx** [comment]
I am open to `Sign Up`. The case against it was that it signals newsletter rather than "give us your email so you can get more involved via events, projects, etc, etc."

**Comment by hannahkane** [comment]
@jessevondoom - alright if we assign this ticket to you? Let's have a conversation about the options Matthew has laid out and see if we can temporarily unblock us, and clarify the larger issues hinted at here.

**Comment by jessevondoom** [comment]
Hey I'm sorry. I didn't see the notification on this because I had default follow settings on github and found myself flooded with notifications from 232 new repos when I joined the Mozilla group. 

I think this is an important one for the launch to members so let's just go with "Sign Up" for now and we can revise later as needed. Moving from an ambiguous "Support" section name into a more dynamic "Get Involved" naming is more important.

**Comment by hannahkane** [comment]
Thanks, @jessevondoom. This ticket got long. I'm going to close and open two new tickets - one for the page name change and one for the button change.

**Comment by xmatthewx** [comment]
> found myself flooded with notifications from 232 new repos

This is almost an initiation ritual in Mozilla. I think I gained admin powers late on a Friday. Definitely gave me a chance Monday morning to test the limits of my google mail search, label, and destroy skills.
