### ISSUE TITLE
How will Global Sprint show up on the site?

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#407]
The [Global Sprint](https://mozilla.github.io/global-sprint/) (June 1 and 2) is a key moment for the movement. How will the Sprint show up on the site? 

Can we capture the thinking that's already been done about this, and brainstorm new ways it will show up?
 - [ ] "Latest from the Network" - blog post about the Sprint could be in the Featured spot in the week leading up to the Sprint, and a summary post could be in the featured spot after the Sprint
 - [ ] Should the Sprint have its own Offerings page?
 - [ ] "Get Involved" section of homepage - featured spot could be reserved for the Sprint (unless...are we reserving that for Projects?)
 - [ ] Obviously, individual Sprint projects will end up in Pulse, but will there be a way to feature them specifically as part of the Global Sprint on the Projects page? Or should they just show up within the particular issue area they're associated with?
 - [ ] Should be on the Upcoming page

**Comment by hannahkane** [comment]
cc @zee-moz @xmatthewx

**Comment by xmatthewx** [comment]
Thanks @hannahkane for kicking this off. We should definitely create a landing page, even if it's a simple overview that repeats the main page on the Github site. And queue up some news and at least a basic get involved (if not the main box). I'd like to link to the global sprint tag in Pulse (instead of or in addition to the github links ... seems more friendly for a broader audience). 

As mentioned, this is related to @taisdesouzalessa work looking at multiple page items on the site: 
https://github.com/mozilla/network/issues/343

**Comment by xmatthewx** [comment]
cc @acabunoc @auremoser

**Comment by acabunoc** [comment]
If it helps, the 'featured projects' tab on the global sprint site is populated 'mozsprint, 2017' tags

https://api.mozillapulse.org/entries/?search=mozsprint+2017

**Comment by xmatthewx** [comment]
This is done! Yay sprint.
