### ISSUE TITLE
Landing page copy for Training 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#44]
One of our featured offerings will be a Training, a mini DIY experience distilled by @zee-moz from the open leadership training series.

We need to craft a landing page and join form for this offering. It should follow the pattern we're creating for internet health (WIP) #29.

We can adapt content [already crafted](https://docs.google.com/document/d/1OuBI2L-8gszdQ3dtFCGn6xvKb8veC-LC2shpr04rFJ0/edit) by @zee-moz. 

@KevZawacki @HPaulJohnson – can you take a look and propose a draft? It should be relatively quick. Likely just needs a connection to join. 

 - I like @zee-moz's statement, "Think of this short course as your launchpad into the Leadership Network."
 - Maybe we say something like "Join to learn more about this and other training opportunities," while still offering a direct link.

**Comment by KevZawacki** [comment]
@xmatthewx Happy to help. Possible copy [here](https://docs.google.com/document/d/1MDfeLsJimZm6glqOQENv-aOe_XOTgT-j0H-NJo39FXs/edit#bookmark=id.qzz543u35gdn) -- let me know if I should expand.

**Comment by xmatthewx** [comment]
hey @acabunoc – as you saw on the site prototype, at some point in the not too distant future we aspire to have an "offering" for training on the homepage. That item will link to a page on the new site. Kevin crafted some [copy](https://docs.google.com/document/d/1MDfeLsJimZm6glqOQENv-aOe_XOTgT-j0H-NJo39FXs/edit#bookmark=id.qzz543u35gdn). It would be great if you and Zannah could review it. Alongside that will be a form to join the network and a link to the training(s). 

Make sense? Let's discuss async or on a call.

**Comment by acabunoc** [comment]
This looks great to me!

One point of clarification -- this copy looks generic enough to apply to several of the open leadership offerings we have:

- A) self-directed, available to anyone, 1-2h, "open leadership 101" @zee-moz recently made
- B) cohort-based, invite-only (w/ application process), 3 month mentorship program aka "open leadership training" that I've been working on
- C) everything in-between the two

I'm assuming the form will point people to A). Once they complete A), they will see options to apply for B) or do C). Is this what you're thinking?

**Comment by xmatthewx** [comment]
I think Yes. The request to join is tied to the simpler, self-directed 101. And... we don't want to block people from the content. Without distracting or overwhelming them, we might still link to richer details. Maybe? Maybe not.

**Comment by acabunoc** [comment]
That makes sense, thanks! Just wanted to clarify since @zee-moz is taking the lead on that version.

Also, I've spoken to a few others about leveraging this launch to solicit applications for the longer 3-month Open Leadership Training. Is it possible to put a call of applicants somewhere?

**Comment by xmatthewx** [comment]
3-month training seems like a good carrot to lure people to join. :carrot: I think it's still an open question on how to best frame this.

**Comment by xmatthewx** [comment]
@hannahkane – probably useful to schedule a conversation with @zee-moz and @acabunoc. Kevin drafted some content above. Let's see if it works as a connector between Homepage Offering and OLTS (whether it's sign-up or mini-course). 

Page will follow pattern set for health report here: https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/216715361

**Comment by hannahkane** [comment]
@zee-moz, @acabunoc, and I met this morning to hash out some minor copy edits, reflected in [this doc](https://docs.google.com/document/d/1MDfeLsJimZm6glqOQENv-aOe_XOTgT-j0H-NJo39FXs/edit#bookmark=id.qzz543u35gdn). 

Still not finalized. In particular, we need to:
 * Choose a short summary for the homepage (some options included in the doc)
 * Draft copy for the "Join Our Ranks" CTA

We had some questions about the page layout—whether it's confusing to have two competing CTAs on the page, and whether the training-specific CTA is going to land below the fold. ( @xmatthewx - Feel free to move these questions to a separate ticket, or perhaps save them for a later day, since they're outside the scope of the task at hand.)

We also had questions about the mechanics of listbuilding. Will we be doing anything to ensure that people aren't given the same CTAs multiple times? e.g. If someone signs up via this page, should the first email they get be a reiteration of the "take the mini-training" CTA, or should we assume they've already done that? I don't think this is a major concern, but maybe we could summarize the mechanics of our overarching engagement strategy at some point. 

@acabunoc and @zee-moz - as a separate task, will you be working on a more specific post-site engagement plan, detailing how we can engage interested people in the full spectrum of our training offerings? Let us know if we can help with that.

**Comment by hannahkane** [comment]
ping @zee-moz and @acabunoc - have you had a chance to think on this more? Do you think we can have content for the homepage feature card and the interstitial page by end of next week?

**Comment by zee-moz** [comment]
yes! I will take a look at it today or tomorrow. @acabunoc we can review together. 😄

**Comment by zee-moz** [comment]
@xmatthewx @hannahkane @acabunoc new Join Our Ranks copy in the doc; I've also edited the description of the training to clarify that it's an intro to open, not a comprehensive learning experience. 
Let me know if you need anything else! 😸

**Comment by xmatthewx** [comment]
bumping forward to this week's milestone

**Comment by zee-moz** [comment]
@xmatthewx @acabunoc @KevZawacki @hannahkane I just made some very small edits, can everyone take one last look, and if it's ok we can call this the final version and close the issue?

**Comment by KevZawacki** [comment]
New edits look good to me!

**Comment by hannahkane** [comment]
+1 from me, too.

**Comment by hannahkane** [comment]
Putting final copy here for implementation:

**Copy to be used on homepage to link to this interstitial:**
Leadership Training for Collaboration 

**Copy for interstitial page itself:**

[Header] Leadership Training
[Subhead] The skills you need to build a healthy web.

[Graf ] 
Open Leadership 101 is your introduction to “working open.” Learn the basics of participation, collaboration, and sharing on community-driven projects. Discover what working open can do for your project, and explore open projects from across the Network. Think of this free, hour-long online course as your launchpad into the Leadership Network.

[Graphic]

Join Our Ranks
Add valuable skills to your leadership toolkit, and find like-minded people and projects across the Network.

[Button] Start your training

**Comment by taisdesouzalessa** [comment]
Do you need the mockup for this one @gvn? It is the same template as the others but if it saves you time I can build it.
