### ISSUE TITLE
Slides for Board meeting

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#470]
As discussed with @sabrinang @taisdesouzalessa @xmatthewx and @jessevondoom, let's develop some board slides exploring potential future iterations of the site, for Mark to share at the June 5th board meeting.

Focus will be on better telling the story of connections between people in the Network, and better telling the story of Internet health.

How's this for a proposed timeline:

- share early drafts with @jessevondoom and @xmatthewx on Tuesday, May 30.
- quick iteration; share with Mark Surman for his feedback on Wednesday, May 31
- final draft for board EOD on Friday, June 2

The board meeting slides are the immediate task in front of us, but we'll keep working on these after the board meeting and will solicit input from stakeholders, including engineers.

**Comment by xmatthewx** [comment]
We reviewed progress. Next steps as I heard them below.

**>> Please comment if you have different understanding or opinion.**

Single slide for **"From the network" feature**
 - should include Coral intro, contributors, and news. 
 - might add project(s) Talk and/or Ask as an element
 - this should fill the slide. no need to show more of the homepage. 
 - no need to explore feature with different content. we can do that after the board meeting
 - let's get a draft slide in front of Jesse today, to propose and implement revised copy before meeting with Mark.

Single slide for **hero direction**
 - no need to show more of the homepage. can be an expression of the hero direction, not literal UI
 - we can present two options to Mark for feedback, but both should be ready to go without footnotes
 - we might try (or maybe not) if both options can fit nicely on a single slide to show that we're in exploratory state. [demo](https://docs.google.com/presentation/d/1QEfeQ4LEg8p9UXigdnp4zzgLTpuoje2d4qR5De30xs8/edit#slide=id.g22b24d6773_1_4).  
 - one option should be the blue people option. could include overlay of some lines from the deck. maybe geography. maybe lines and labels for the 5 issues. 
 - another option could be more abstract, pulling in people line art

**Comment by taisdesouzalessa** [comment]
Adding the full slide deck here so we have it as a future reference:
https://docs.google.com/a/mozilla.com/presentation/d/1QEfeQ4LEg8p9UXigdnp4zzgLTpuoje2d4qR5De30xs8/edit?usp=sharing

**Comment by taisdesouzalessa** [comment]
I'll work on the "From the network" feature - I'll have the slide with the module as we saw in the meeting today and some other explorations of storytelling in this specific module. By EOD Jesse will have some options on slide format. Does that work for you @jessevondoom and @xmatthewx?

**Comment by taisdesouzalessa** [comment]
I'll work on the "From the network" feature - I'll have the slide with the module as we saw in the meeting today and some other explorations of storytelling in this specific module. By EOD Jesse will have some options on slide format. Does that work for you @jessevondoom and @xmatthewx?

**Comment by jessevondoom** [comment]
@taisdesouzalessa Perfect. Thank you!

**Comment by taisdesouzalessa** [comment]
Worked on the "From the network" feature from slide 49 on. Please take a look at them and let me know your thoughts. I added comments to the slides to explain little things. @hannahkane @xmatthewx @jessevondoom

**Comment by sabrinang** [comment]
Worked on the "hero direction" from slide 47-48 as well and any feedback would be great.

**Comment by jessevondoom** [comment]
@sabrinang So I still like the illustrations more than the magnetic waves — though it's funny they feel sort of similar. But both for the consistency and the reminder that these concepts come down to people and community impact I think it's stronger. 

I like how some color from the photo sneaks in on the light version, but I think I generally prefer the darker one. Think we could explore using a gradient like the blue-to-green on slide 48?

And lastly, I love the abstract node background stuff on slide 48 — not sure it's right for the hero but I think it's a design sketch we should keep around for sure. Maybe to use as the background of a panel, or similar? It may also just need a little more time than we have right now, but I think it's got real potential.

**Comment by jessevondoom** [comment]
@taisdesouzalessa I think these are all great, and I could see each of them having a home on the site. Let's work on slide 50 for now, because I think it can show everything we want to illustrate in a single shot. Here are a few changes I'd suggest, mostly pretty minor:

1. Let's change "Highlighted project's collaborators" to "The people of The Coral Project"
2. Andrew's description: "Andrew started The Coral Project so people don't have to be afraid of reading the comments." (Open to suggestions, but I tried to match the length since this is internal-only.)
3. I liked the social link rollover styles you used on slide 10. Should we try that here on one of the not-Andrew people? It would be nice to show another connection point.
4. This is probably the biggest one, and I'm torn. I like the learn more / case study part at the end, but also feel like we're missing a "get involved" element. Could we play with something here? Thinking we could use that space and show a couple ways people could help like "Amplify their work" with a twitter icon and/or "Lend a hand" with a github icon. Would love other suggestions, too — just want some kind of clear indicator that there are mechanisms for interaction.

**Comment by jessevondoom** [comment]
@xmatthewx Yeah exactly. Sorry if that wasn't clear, @sabrinang.

**Comment by sabrinang** [comment]
Thanks for the feedback @jessevondoom @xmatthewx I updated top of slide 48 with iterations of people + line art + blue-green gradient (dark/light).

**Comment by jessevondoom** [comment]
These look great. I think I'm partial to the lighter version (top right of slide 48) but either of the top two options would work really well. Love the balance between colors, showing people, and incorporating the illustrations from the main deck. Feels very vibrant.

**Comment by taisdesouzalessa** [comment]
@jessevondoom I did the requested changes in the slide 50. 
I added the "learn more" link to the featured part (that could be the link to the case study) and the final ask for this section is geared towards contributing, as you suggested. 

I love the idea of adding "Amplify their work". I think that in this section may be too soon to ask for that since the users didn't have the opportunity to get to know the project in a deep way yet. We could add this button in the case study section, prepopulating the tweet with some quote or content we think it is nice to highlight. Something like that (example extracted from a blog):

<img width="843" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/26644707/7f637868-45ea-11e7-9816-77428d04056f.png">


Let me know what you think :).

**Comment by jessevondoom** [comment]
This looks really solid. It's easy to see how the same format could apply to open web fellows, other projects, and other groups. Nice work. And I think you made a good decision on skipping the amplify bit in here — definitely feels like something for a case study or project profile page — and I like this example you dug up...was thinking similarly with a quote/prepared tweet. 

I'll share these with Mark and see if there's any additional feedback, but I think we can turn our thinking to presentation — these are going into either one or two full-bleed slides. We should prepare them for Lainie a couple different ways:

1. Two slides: one for the hero work (48) and one for the UI elements (50.) 
2. One slide: can we show them together in a way that does them both justice? 

We may also be able to do a printed poster layout that would allow us to show more alternates, etc. Looking into that now.

**Comment by taisdesouzalessa** [comment]
Hey @jessevondoom, the option 2 is ready for review.

1. Two slides: one for the hero work (48) and one for the UI elements (49)
2. One slide (50)

cc: @xmatthewx @hannahkane

**Comment by jessevondoom** [comment]
@taisdesouzalessa This looks great...thank you!

**Comment by taisdesouzalessa** [comment]
@jessevondoom based on your last comment, it seems there is no further revisions for this task. I am closing this ticket. Feel free to reopen it if you have any new feedback :).
