### ISSUE TITLE
Opportunity pages aren't showing colorful header

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#598]
https://network.mofoprod.net/opportunity/internet-health-report/ should look like https://network.mofoprod.net/about but the colorful bar at the top is missing. (This applies to all `/opportunity/*` pages)

<img width="1246" alt="screenshot 2017-07-25 17 51 24" src="https://user-images.githubusercontent.com/1682681/28595442-e630e416-7161-11e7-9140-19e2a26cf691.png">

**Comment by gvn** [comment]
This is because `master.pug` [changed](https://github.com/mozilla/network/commit/eabb44d675cbfab5dd2c58a6a344fc542789f478#diff-f9e65c84f1e95b5b8928e55186e4747a) (which results in the landing page template changing and needing to be pushed to `network-api`).

Essentially the script that does this automagically needs to be updated to watch for changes to `master.pug` as well as `opportunity.pug`. 🐶

**Comment by alanmoo** [comment]
If this turns out to be a ton of work to update the script, let's just fake it for now (with a commit to `opportunity.pug`) since this flow is going away soonish anyway.

**Comment by gvn** [comment]
You could also pull the compiled template for a manual commit instead of touching `opportunity.pug`.

**Comment by cadecairos** [comment]
Fixed by removing the CI requirements on master - it was causing the git commits from jenkins to not make it to network-api.

I updated the template and CSP, and got it out: https://network.mozilla.org/opportunity/internet-health-report/

![ihr page screenshot](https://screenshots.firefox.com/Ep8Wmuw9ChyjjBOp/network.mozilla.org)
