### ISSUE TITLE
Figure out deployment process

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#607]

**Comment by gvn** [comment]
@cadecairos let me know if anything needs refactoring or if you have any other questions!

**Comment by cadecairos** [comment]
My plan here is to set up the Heroku app so that it first starts the NodeJS Heroku buildpack, which will run `npm install`. We will need to add in `heroku-postbuild` to our npm scripts, to trigger the "build" npm script after dependencies are installed. (using this hook instead of the "postinstall" will prevent headaches for localdev - I hate post install hooks that rebuild when I don't need it to.)

After the nodejs bits are done, we'll fire up the python buildpack, which will install dependencies in requirements.txt. The first issue we have here: In order for this to work properly, we need `requirements.txt` to be at the [root of the project](https://github.com/heroku/heroku-buildpack-python#see-it-in-action), which isn't the case if it's submoduled.

We can continue to use a "release" process to run `python manage.py migrate`, and a web process to start up gunicorn.

@alanmoo @gvn @Pomax How can we get that requirements.txt in the root? Should we copy it over now, or should we just add the network-api code in now and restructure where the files are.

**Comment by gvn** [comment]
If possible I think we should copy the entire `network-api` subfolder over to an environment where it can be the root after `npm run build` finishes. 

Once the static assets are built into the `network-api` subfolder the `network` wrapper should no longer be needed.

**Comment by cadecairos** [comment]
Heroku won't let us change the  `$BUILD_DIR` variable that it sets, which the buildpacks rely on for detecting if the buildpack will work, so I don't think that's an option here. We need to ensure that `requirements.txt` is in `$BUILD_DIR`, which is the project root.

**Comment by cadecairos** [comment]
OK, after moving the [requirements.txt file and the Procfile into the project root, and adding in a heroku-postbuild hook](https://github.com/mozilla/network/pull/630), the build process [seems to be working](https://dashboard.heroku.com/apps/network-api-unity/activity/builds/5ade5c2e-c586-4521-b418-2e2fec152f5d).

I have noticed that static assets for the admin interface are 404-ing. Pretty sure that's unrelated to the build process. either in our configuration in the code, or in the environment variables.

https://network-api-unity.herokuapp.com/
