### ISSUE TITLE
Implement mini-site functionality (MVP)

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#623]
The goal of this epic is to use existing templates and add the ability for editors to create subpages with their own navigation hierarchies (down one level) from the existing Opportunity pages.

See a prototype at https://taisslessa.github.io/simple-model-ui-v4/index.html

**Comment by xmatthewx** [comment]
I don't think that header image support is part of MVP for this, b/c it will introduce lots of different complexity we haven't thought through yet. I suggest we focus on core functionality and achieving good authoring UX in this first round.

**Comment by alanmoo** [comment]
Agreed, just created some tickets for that as placeholders. They're staying in the backlog for now, though feel free to remove them from the epic.

**Comment by alanmoo** [comment]
This may be a good epic for @arush0311 to take on if others don't have bandwidth for it this sprint.

**Comment by gvn** [comment]
I can handle the front end if @arush0311 can do the backend portion. I just assigned myself to #619

**Comment by alanmoo** [comment]
Not sure why I closed this...

**Comment by taisdesouzalessa** [comment]
Hey @gvn I will do the QA for this page and I was wondering if this is the one I should be looking at:
https://network.mofostaging.net/opportunity/net-neutrality-groups/

**Comment by gvn** [comment]
Yeah, although we're saying that none of the multipage pages should have signup forms for now.

**Comment by xmatthewx** [comment]
Looking great. 
 - form: agreed. doesn't work as sidebar. fortunately, we're looking to move forms down below and full width by default for pages. 
 - sub-nav: seems like we'll want less line-height on two line items and/or more space between items. 
 - bonus: great to see that video embeds are working.

**Comment by taisdesouzalessa** [comment]
Nice page :). 

+1 to Matthew's comments above and:

• please make video responsive (it is cutting on the right) - 
<img width="300" alt="image" src="https://user-images.githubusercontent.com/22157921/29944165-3e8d9dc8-8e51-11e7-8e10-56298e86a64a.png">

• menu should go to top on mobile instead of staying on the sidebar:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/22157921/29944263-bcb22912-8e51-11e7-8739-100c1e839778.png">
Prototype here: https://taisslessa.github.io/simple-model-ui-v4/index.html

**Comment by gvn** [comment]
> sub-nav: seems like we'll want less line-height on two line items and/or more space between items.

Can you specify the tweaked measurements? I copied the CSS straight out of the Sketch file...

**Comment by gvn** [comment]
A couple other things:

- The responsive video is unrelated to this ticket, so we should file a separate issue for that.
- I'd also like to file another ticket for the navigation transform, because that wasn't MVP from what I understood.

**Comment by taisdesouzalessa** [comment]
> Can you specify the tweaked measurements? I copied the CSS straight out of the Sketch file...

I tested here and 1rem seems to work. The Sketch file had 24px of distance between the elements...as desired. I guess visually we had the right distance but maybe the style in Sketch didn't match that? Not sure what happened...

<img width="264" alt="image" src="https://user-images.githubusercontent.com/22157921/29945498-3308efca-8e56-11e7-9fd9-694a06ac258f.png">

**Comment by taisdesouzalessa** [comment]
> The responsive video is unrelated to this ticket, so we should file a separate issue for that.

Cool, I can do that. I updated the my comment to reflect this request :)


> I'd also like to file another ticket for the navigation transform, because that wasn't MVP from what I understood.

Done in the comment as well. From the UX perspective, the top menu should be in the MVP otherwise this page has big usability issues on mobile. If adding menu as dropdown has a big cost in terms of time we can open a design ticket to study alternatives and work together on it.

**Comment by xmatthewx** [comment]
I do think this is dependent on mobile layout for nav. Menu is just too squished to be usable on small screens.
