### ISSUE TITLE
Analytics: identify events and goals

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#64]
A primary goal of the site is to increase membership of people with leadership potential. Let's plan our analytics to help us track efforts toward that. 

First step: identify key events to track

Second step: gather advice from @vojtechmzl

**Comment by xmatthewx** [comment]
Most user action will be of three types:
 - Join form
 - Featured "Offering" to Join form
 - Outgoing links to strategic distinations  


### Events 
 - User taps Join button in header 
   - User submits Join form
 - User submits Join form on homepage 
 - User taps a featured "offering"
   - User submits Join form connected with offering
   - and/or... User follows outgoing link to the offering

@vojtechmzl – is it useful to track some outgoing links as events? For example, our member profiles will include links to their twitter/linkedin, a useful path to building network strength. Can we gain insight by tracking these as events? To see how this action trends in aggregate? Or do we have all that info without event tracking?

Here are some key outgoing links
   - Link to a member's Linkedin or Twitter (contributes to network strength)
   - Link to a featured "Offering" (e.g. Internet Health report)
   - Link to Pulse or a Pulse item
   - Other links? Probably fine tracked just as links. 


cc @taisdesouzalessa @sabrinang @gvn

**Comment by vojtechmzl** [comment]
Hey Matthew,

The list of events around the sign up process makes sense. Given the site's role in serving as a directory of a lot of different activities within Mozilla I think it's a good idea to set up events that track outbound links, so that we can distinguish between abandoned visits (i.e. people who simply left) and people who engaged and followed onto a purposefully linked entity. There are some built-in functionalities to analyze outbound links, but events are I think the best option.

Events in GA can take on three attributes -> category, action and label. That means things can be neatly organized into sections. For instance 

Category: People
   Action: Clicked on Profile
      Label 1: LinkedIn
      Label 2: Twitter

Category: Programs
   Action: Visited an offering page
      Label: [name of offering]
   Action: Clicked through to offering
      Label:  [name of offering]

Once events are passed in this way to GA, we can set up specific Goals in order to track for instance how many people clicked through to people's social profiles. We can then also utilize those events in building funnels to best understand how people engage with the site before they sign up.

**Comment by xmatthewx** [comment]
Thanks @vojtechmzl, this is great. It'll be especially useful for our "offerings"

For some, the flow will be a simple experience: tap b/c you're interested, join to get access (e.g. apply for a fellowship, or propose a mozfest session). 

Others are more weird and will require experiments: tap b/c you're interested, join and go enjoy something else (e.g. read internet health report). Because we ❤️ open and distributed things, there will always be things we offer elsewhere, without a hurdle to join first.

**Comment by vojtechmzl** [comment]
That makes sense. Since most of our sites have GA installed, we can always set up dashboards that pool data from multiple sites to get the full picture of the user journey, not just the steps taken on the new network site. Lots of exciting stuff here!

**Comment by gvn** [comment]
@vojtechmzl Do you have a `script` tag that I can throw in to get baseline tracking set up for now?

**Comment by xmatthewx** [comment]
Will we need a devops tickets to setup property? 

I believe we said we'll start with standard tracking, enhance when ready.

**Comment by vojtechmzl** [comment]
Once the final URL has been decided, we can ask Chris to spin out a new GA property. Should be fairly straightforward. Do we know what the URL will be?

**Comment by gvn** [comment]
Can we add basic analytics to https://network.mofoprod.net/ ?

**Comment by vojtechmzl** [comment]
Just to follow up, I've filed an [issue](https://github.com/MozillaFoundation/mofo-devops/issues/470) with the devops team, so hopefully we should have the tracking code soon. Sorry for the delay on this.

**Comment by vojtechmzl** [comment]
And here it is:
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-87658599-6', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by gvn** [comment]
The snippet is added. Leaving this open for further work post launch and reducing to P2.

**Comment by gvn** [comment]
@vojtechmzl The snippet will be on https://network.mofostaging.net/ shortly if you want to confirm.

**Comment by taisdesouzalessa** [comment]
In discussion is a separate doc with Matthew. Once we refine the doc with the main event and goals, I'll post it here.

**Comment by taisdesouzalessa** [comment]
Closing this ticket - creating a new one with simple events to track at this first stage.
