### ISSUE TITLE
Provide design support for MITI page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#692]
The MITI (Mozilla Information Trust Initiative) Project needs a landing page on the Network site. I've started to build it, based on the copy we've received, but it needs some design love, perhaps in two parts:

1) What can we do immediately to improve the page's appearance before the September 1st deadline?

2) This page might serve as (another) exemplar of the type of content we expect to see more of on the Network site. Does it inspire any feature ideas for the future?

Discussed with @taisdesouzalessa, but will discuss further during grooming.

**Comment by taisdesouzalessa** [comment]
Hey @hannahkane I made the changes that fit into the first criteria - quick wins we can do to meet the deadline. Some observations:
1. I added "Mozilla Information Trust Initiative" as the title of the page, even though we have it in the header. The reason being is that this info helps to orient users on the page and this is likely the first thing they will see due to its hierarchy.
2. I added "We are..." before "investing in people, programs..." because I had a weird text gap in the final design so adding some extra words made it better. Let me know if it is ok.
3. Are we adding a button (A)? If so, where should it link to? If not, we should remove the sentence. From my understanding, A and B are different things, right? 
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/22157921/29727139-8858f3e0-8987-11e7-831a-70409b94c4cc.png">
4. I styled the "Upcoming Events" as links but we don't have those links yet. If they don't exist, my suggestion would be to add something like "more info coming soon" in each one of the bullet points or exclude this box because the expectation is that people would find more info.
<img width="435" alt="image" src="https://user-images.githubusercontent.com/22157921/29727328-33196ff8-8988-11e7-9358-8c1ffbf21e9d.png">

Hannah, let me know if you need any revisions - I didn't publish the page but itis modified in the CMS.

**Comment by hannahkane** [comment]
Thanks, @taisdesouzalessa. Very nice job. I've made a version of this on the staging site so I can share it with the MITI team for feedback.

Good call on the page title and adding "We are." Thanks for those changes. I rewrote the sentence pointing to the form, as I believe the intent was to refer people to the sign-up form.

Did this spark any ideas for follow-up tickets you'd like to file?

**Comment by taisdesouzalessa** [comment]
@hannahkane great! Let me know if there is anything else I can help with. 

I have some follow up tickets. I took notes of the challenges I experienced while using my "editor" hat while tweaking the MITI page. 

Tickets: #704 and #690

**Comment by hannahkane** [comment]
Excellent. Thanks, @taisdesouzalessa. Closing this ticket.
