### ISSUE TITLE
Refresh Join CTA and Form

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#71]
Depends on more info from Chris and Rizwan.

**Comment by xmatthewx** [comment]
Discussing with @KevZawacki [in a doc](https://docs.google.com/document/d/1-oG6aZJYau7UsKVv76WdKVjWDWg7ffpP9hsKlFTWsYI/edit#heading=h.p7fz1t5n355o).

**Comment by xmatthewx** [comment]
There are 3 questions for @taisdesouzalessa @sabrinang  to consider after I hand them new draft form: 1) is form on homepage or is there just a small cta that links to join page? 2) is cta/form connected with get involved box? 3) is news above or below get involved?

**Comment by taisdesouzalessa** [comment]
Sabrina and I worked together on the following options:

1. [Mockup - form in the homepage](https://invis.io/ZJ9YTAGEA#/222853316_Home_Page-V1a)
2. [Mockup - small CTA](https://invis.io/ZJ9YTAGEA#/222853318_Home_Page-V2a)
3. [Mockup - form in the homepage/news in the middle](https://invis.io/ZJ9YTAGEA#/222853317_Home_Page-V1b)
4. [Mockup - small CTA/news in the middle](https://invis.io/ZJ9YTAGEA#/222853319_Home_Page-V2b)

@xmatthewx @hannahkane  I think the option 2 works better because the user flow is less busy and I would assume the users are more in the exploration mode at this point and adding a longer form block may detract from the goal of discovering. 

I would love to hear your thoughts on those options and @sabrinang's as well.

**Comment by hannahkane** [comment]
I think I'd prefer either 2 or 3. I feel like a form in the middle of the page could be quite distracting, and, as @taisdesouzalessa, could detract from the discovery goal.

Can we use optimizely to test how form vs CTA affects conversion?

**Comment by taisdesouzalessa** [comment]
Here is the standalone "Join the Movement" page:
https://invis.io/ZJ9YTAGEA#/222863031_Join-The-Movement

@hannahkane flagged in InVision that we may need to add the Privacy Notice checkbox before the Join Us button due to legal reasons. We can talk about that in the stand tomorrow and I can do the changes across the prototype.

**Comment by hannahkane** [comment]
Is this duped by #156?

**Comment by taisdesouzalessa** [comment]
Here is the new standalone page:

DESKTOP:
https://invis.io/ZJ9YTAGEA#/222863031_Join-The-Movement

MOBILE:
https://invis.io/ZKAIKN1MN#/223591972_MOBILE---Stay-Connected

**Comment by KevZawacki** [comment]
Possible to trim the message a bit? To:

**Stay Connected**
Sign up for opportunities and news related to a healthy internet.

**Comment by taisdesouzalessa** [comment]
Thanks @KevZawacki! I updated the links to reflect your suggestions. 

DESKTOP:
https://invis.io/ZJ9YTAGEA#/222863031_Join-The-Movement

MOBILE:
https://invis.io/ZKAIKN1MN#/223591972_MOBILE---Stay-Connected

@xmatthewx @hannahkane @sabrinang those mockups are ready for your feedback :). Please let me know if everything is good to go (or if the structure is ok) so I can send them to @gvn - issue #165 mentions this ticket.

**Comment by taisdesouzalessa** [comment]
> `Is this duped by #156?`

@hannahkane I believe #156 is more like a reminder list of everything related to the "Join Us" subject while we have individual tickets to track specific issues. I have been linking the individual tickets #156. Not sure it is the right thing to do. Let me know if it is confusing...

**Comment by xmatthewx** [comment]
Closing this. We can track implementation in: https://github.com/mozilla/network/issues/188
