### ISSUE TITLE
Make video responsive on user authored pages 

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#711]
• please make video responsive (it is cutting on the right) - 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/22157921/29944165-3e8d9dc8-8e51-11e7-8e10-56298e86a64a.png">

**Comment by gvn** [comment]
So digging more into this I realized that the embed is just custom added HTML with hardcoded dimensions.

I'm not sure if Mezzanine has WYSIWYG video embedding functionality that we can enable, but if it does we should turn that on instead of requiring people to add their own embed code.

Alternatively we could add a video URL field to the page model and embed via JS.

If we do leave this as custom code we may need to add some JS to give it responsive behavior.

Setting this as "needs discussion"...CC: @alanmoo @xmatthewx

**Comment by xmatthewx** [comment]
Post MozFest, @alanmoo or someone can look to see if there's a quick solution for common embeds via a mezzanine plugin. Otherwise, we'll solve this with thumbnail links until a need arises for a core official foundation page.

**Comment by gvn** [comment]
I found a Bootstrap solution that seems to work:

https://v4-alpha.getbootstrap.com/utilities/responsive-helpers/#responsive-embeds

It's not the most straightforward to get it in there, but it works:

https://network.mofostaging.net/opportunity/net-neutrality-groups/test-sub-page/

**Comment by taisdesouzalessa** [comment]
Removed the blocker notice: this issue is not blocking #191 anymore. I'll try Gavin's approach on staging and close this issue once I am done.

**Comment by taisdesouzalessa** [comment]
It worked and the problem is solved using @gvn suggested approach (yay!). #191 is closed and the step by step process was added to the [Network User Guide](https://mzl.la/cms-guide).
