### ISSUE TITLE
Discuss constraints: Display Terms before first time Login

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#738]
When a new user logs into pulse, we capture data and create an account. 

Now that we're adding profiles, before they do this, we need to make this clear, display a link to terms, and off a checkbox for them to agree. No check in the box, no entrance. 

Given that we're using g-auth, what's the typical pattern for doing this? What capacity do we have to start a sign-in, but pause it for a first-timer who hasn't yet agreed to our terms? And cancel it if they don't? Or, do we need to design around this and assume all users will have the same auth flow?

Likely a question for @Pomax. cc @kristinashu

**Comment by Pomax** [comment]
I don't quite understand why it's important to tell people we create a profile when that profile by default has zero information in it. The word "profile" seems oddly loaded: what we create is a data structure that acts as a link between a gauth-dictated user object, and our site data. By default, there is nothing else in that model so functionally it's not "a profile" until the user actually goes in and adds information that makes it one.

Can you point to other sites that have this kind of flow? I can't think of any other sites where I've run into this flow, and it feels a bit artificial (especially where "not wanting a profile means you don't get to log in"... there is no data in the profile until you put it there, so I don't see a clear justification for forbidding users entry)

**Comment by xmatthewx** [comment]
Let's set aside questions about profiles. Regardless of that, we have another issue to address. 

As soon as someone uses google auth, we record their email in DB. True? We need to offer our ToS before that happens. We currently do it after login, before they submit an entry.

I'd like to resolve this, but I'm not sure whether g-auth offers a hook to check if a user already exists, and then send them on different paths accordingly. If they do have a hook, we can offer sign-in without a terms checkbox, redirecting new users to sign-up. If they don't offer a hook, we'll need to display a terms checkbox for all sign-in, even for existing users.

**Comment by Pomax** [comment]
This is misleading phrasing, which I think is important to catch in this case: we record "an" email address, not so much "someone's" email address. But as you point out, the important part is that we give users ToS to agree to, and figuring out where to do that is important.

As it is impossible to persistently record a user's choice in accepting the ToS until there "is" a user as recognized by the backend, which it cannot do until the user logs in, I would suggest the following: when a user wants to log in, they are taken to a page that gives them a big login button and a text that says "by logging in you agree to our [Terms of Service]()" or something similar, such that the act of logging itself constitutes consent. This avoids any complications around interrupting a black box login procedure, or storing consent status in a browser's cache/localstorage/etc, or checkboxes that really only serve as an extra interaction step without function.

The most important part here though I would image is having a well written ToS page that can be linked to, so that people can know what we expect from our users. And then we'll also have to think about how we notify all our current users of the fact that the ToS are about to change (or in this case, come into being =)

**Comment by xmatthewx** [comment]
Thanks @Pomax. We'll design around the black box login as you suggest, see if we can pass legal muster.

**Comment by kristinashu** [comment]
Here's a comp of the most basic page. If we don't have a checkbox then knowing if a user already has an account or not becomes less important. We will still need to work out the copy tho.

![sign in 2x](https://user-images.githubusercontent.com/1068783/30830830-39c70312-a1fa-11e7-9e3a-fd54eb045ba3.png)

**Comment by kristinashu** [comment]
Oops wrong ticket, moved to https://github.com/mozilla/network-pulse/issues/694
