### ISSUE TITLE
Remove circular dependency in build system

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#748]
This likely involves changing the build order of the static site and the API so that the JSON can be generated before the static pages are built. How we get the JSON into the build process is an implementation detail for whoever works on this.

**Comment by Pomax** [comment]
To be more specific, the issue here is that we have two components: a mezzanine server, and a static asset generator.

- the generator requires mezzanine to be running in order to get the data it needs to generate the assets, and
- the assets need to already be available for mezzanine's `collecttemplates`/`collectstatic` to do the right thing

This isn't a "true" circular dependency, but it's problematic enough: it would require running mezzanine, then the asset generator, then collect templates/assets for mezzanine with probably a restart. Which is quite weird.

**Comment by gvn** [comment]
I'm fixing this by migrating all our CMS-driven static components to React/XHR based components.

Slack convo for reference:

```
so i’m starting to think that maybe we should refactor everything that is fueled by mezzanine-provided JSON to a react component pulling XHR (edited)


[12:53] 
that way we can point it to whatever instance of mezzanine data we want and should eliminate the circular dependency since it’s always pulling from the latest data at runtime (instead of needing it first for build) (edited)


[12:54] 
i’m already refactoring the homepage, and the people page is also close since it’s react, but using bundled JSON (can switch to XHR easily) (edited)


[12:55] 
also, this means CMS updates will take effect instantly on prod
```

**Comment by Pomax** [comment]
ooh, nice! If mezzanine sends proper 304's, the perf hit would probably be pretty low too.
