### ISSUE TITLE
User journey - Fellowship pages

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#858]
User journey

- [ ] 1. from hearing about Fellowships to being in one cohort

- [ ] 2. from belonging to a Fellowship to updating projects and connecting to other Fellowship members

- [ ] 3. from learning about the existence of Fellowships to getting educated about it in order to use the info learned (media or internet activists).

**Comment by taisdesouzalessa** [comment]
Here are the journeys:
1. https://invis.io/GPDZCQDQJ#/258657198_1-From-Non-Member-To-Being-Cohort
2. https://invis.io/M5DZCXAN2#/258657199_2-From-Fellow-To-Ending-Fellowship
3. https://invis.io/VMDZD1IF4#/258657200_3-Media

To navigate that in the order, please click on the blue dot to the left(that should be the starting point) and hit next. It will guide you through the questions I had while thinking about the system. Please comment there, add your thoughts and paths that I may have missed. 

@hannahkane @xmatthewx @jessevondoom - looping you 3 for feedback. Feel free to add more people as you see fit.

**Comment by taisdesouzalessa** [comment]
One curiosity: 

[Here](https://invis.io/5VDZDH2SZ#/258664528_Christine-Zhang-Story-Engine) is a real user journey from Christine Zhang (featured in Story Engine). She fits into our "Pepper, the Professional" persona and I think it is very cool that some of her pain points will definitely be solved with this page. Thought it was worth it to share.

**Comment by taisdesouzalessa** [comment]
I will be working on some MozFest materials with Sabrina - however, please feel free to comment, give feedback and discuss this issue :)

**Comment by auremoser** [comment]
Hey there, I'm pretty toe up with Mozfest floor prep, host org onboarding and fellows arrangements for Mozfest, but I've tried to address your questions below

**Journey 1:**
> You asked a great question about how much info potential applicants have by the time they come to the site. I think @auremoser might be a good person to help answer that.

To be honest, the majority will probably find this page through social media shares and blog posts from our comms team. I doubt many will fall into it, since it's not a topline nav item. It's possible people will hit "get involved" and get curious about our fellowships but I think that the terms are pretty self explanatory, most people will know what a fellowship involves and can read the FAQ or the kind of simple info we have on the [science site](https://science.mozilla.org/programs/fellowships/fellows). 

When applications are open we add a banner to push people to the application, when the applications close we add `"applications are closed for YEAR, check back in MONTH"`; I imagine the network site will work the same way and point to our FLUXX application from the Network site.

> The question of whether we want potential Fellows to contact past Fellows is a great one. Maybe something @auremoser or @community-impact could weigh in on?
We provide fellows with the master contacts of all fellows from previous cohorts so they can setup collabs; I think any alumns we feature are pretty willing to being contacted over Twitter or via any channels identifiable from their personal websites. We defintitely would love to see more collaboration between fellows, but I'm not sure the Network site needs to be the engine that enables those collabs particularly.

**Journey 3:**
> Your question about "who else besides media and internet activists" is a good one for @auremoser and @community-impact
I'm not very clear on who this journey is intended for (is it folks who don't want to be fellows but rather want to reach out to fellows or learn more about our program?); if it's that, we'll probably get a mixture of scientists, educators, media, artists, activists, nonprofit folks and developers, given the fellowships we offer and the people who might be attracted to the program based on the demographic/thematic foci of those fellowships. I hope that makes sense and isn't too vague.

Let me know if I missed anything!

**Comment by taisdesouzalessa** [comment]
Thanks, @hannahkane for the thoughtful comments and linking to other people and thanks @auremoser for carving some time in your busy schedule to answer those questions. They are very valuable to design so I can put myself into the Fellows' shoes and make sure their main needs (and ours as an org) are addressed.  Thanks a million!

**Comment by taisdesouzalessa** [comment]
Checked user journey with Amy and Jesse as well. Their observations, together with Aurelia's and Hannah's answered the questions I had. Closing this issue.
