### ISSUE TITLE
Review apps don't show s3 assets

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#875]
I think we're still missing an env var or two.

Images with a host of `assets.mofostaging.net` in the staging app instead get a host of
`network-site-staging-pr-874.herokuapp.com`, for example

**Comment by cadecairos** [comment]
@patjouk here's a bit of background: 

- We added fixture data that is loaded automatically when a review app hits the `release` phase (review apps automatically set `LOAD_FIXTURE=True`). 
- Contained within that data are model records that contain URL information for images that were uploaded to `assets.mofoprod.net` (an S3 bucket backed by CloudFront).
- The default configuration for file uploads on review apps is to use file storage on the dyno.
- Once it's all loaded, it seems the URLs being rendered in the Django Rest Framework (DRF) endpoints is getting the app hostname as a URL for the resources, instead of the `assets.mofoprod.net` hostname.

So there are two possible solutions here (maybe?):

1. We see if we can set environment variables relating to file storage, that will use the right hostname with the filepaths stored in the database, thus rendering the correct URL with DRF responses.
2. We see if we can manually update the fixture data so that full URLs are rendered (I'm not sure this is going to work, I think option 1 is our best hope.)
3. We update the paths of all images in the fixture data to point to a placeholder image that is always present in the staticfiles directory!

**Comment by patjouk** [comment]
[First tests](https://network-site-staging-pr-880.herokuapp.com/) from the PR are looking good. There are still broken pictures, but it's because they don't exist in the bucket 😅 . I'm looking into a fix for that.

**Comment by patjouk** [comment]
I've updated the fixture file so that review apps and the staging stack now share the same assets :)
