### ISSUE TITLE
Using ENV variables in template means pipelines still don't quite work right.

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#884]
When we use pipeline promotion, the OG tags (as an example) on the homepage show the staging url, because we're using env variables in the pug file.

Is this a side effect of using XHR instead of Django templating to generate pages?

**Comment by gvn** [comment]
It's a side effect of switching to pipelines because we're no longer rebuilding when we do a prod push, so env references in Pug are left the same as they were on staging.

The good-ish news is after https://github.com/mozilla/network/pull/882 lands there's only 1 env var left being used in a Pug template, and it's `PULSE_DOMAIN` in `pulse-projects.pug`, which is probably also safe to hardcode.
