### ISSUE TITLE
Create 6 user stories based on from our list

### ISSUE THREAD

**Issue by Pomax** [mozilla/network#9]
We want to make a selection of the user stories in https://public.etherpad-mozilla.org/p/network-software-groups to form 6 concrete user stories that we can use to guide our initial work around what we need out of django and how we can make that happen.

**Comment by xmatthewx** [comment]
The user stories here don't represent this site's requirements or goals. I think we're talking about two inter-related but distinct projects. We should meet next week before investing time in this.

**Comment by kristinashu** [comment]
@xmatthewx yes, this django work is much more related to Clubs work than MNL site but we weren't too sure where to file these tickets (and didn't want to create a new repo until we have a better sense of where this work is leading). We did it here since it is loosely relevant to the MLN work, although not the same. Do you still think we should hold off on this?

**Comment by Pomax** [comment]
This is work that we're doing in preparation of a work week, independently of other MLN work, there may have been confusion over which actual project heartbeat these issues were part of.

**Comment by kristinashu** [comment]
@Pomax I've edits down the user stories and identified how it might impact the django admin https://docs.google.com/a/mozilla.com/document/d/112JzKuNtKEcnKK0_fOQiEochG8rBLNhC-V7c2p8JRoM/edit?usp=sharing

Let me know you thoughts, either in the doc or we can chat at the office tomorrow.

**Comment by kristinashu** [comment]
Purpose of these use cases is to then see how easy/hard it will be for Program staff to do them in django.
